.TH dmsub 1 "$Date" "$Revision: 323 $" "PBS TOOLS"

.SH NAME
dmsub \- Submit a data movement job using a variety of methods.

.SH SYNOPSIS

.B dmsub
[arguments] [-f] xfer_file

.SH DESCRIPTION
.B dmsub
is a tool for submitting data transfer jobs described in a number of
forms (dmover/urlpair, rft, stork) using a wide variety of backends
(dmover, pbs/torque, rft, stork) and data movement tools (dmover,
globus-url-copy, rft, stork, supermover).

.SH TRANSFER DESCRIPTION FORMATS

.B dmsub
supports a number of ways to describe a data transfer:
.TP
.B dmover
The native transfer description format of the PSC dmover tool,
described at 
.I http://www.psc.edu/general/software/packages/dmover/
.TP
.B rft
The native transfer description format of the Globus RFT tool,
described at 
.I http://www.globus.org/toolkit/docs/4.0/data/rft/rn01re01.html
.TP
.B stork
The native transfer description format of the Condor Stork tool,
described at 
.I http://www.cs.wisc.edu/condor/stork/tutorial/stork-dagman/#xfer
.TP
.B urlpair
Lines of source and destination URLs separated by white space.  (This
is functionally equivalent to the dmover format.)

.SH DATA MOVERS

.B dmsub
also supports a number of mechanisms to transfer data:
.TP
.B globus-url-copy, guc
Globus GridFTP
.TP
.B rft
Globus RFT
.TP
.B stork
Condor Stork
.TP
.B supermover
PBS Tools supermover, which is a configurable wrapper around
globus-url-copy, scp, and a number of other tools.
.PP
Note that it is not necessary for
.B dmsub
to use the data mover associated with a given transfer description
format or vice versa.  In particular, one can use
.B supermover
to transfer a set of files described in any of the dmover/urlpair, rft, or
stork description formats.

.SH BATCH SYSTEMS

.B dmsub
also supports a number of "batch systems", which includes both
tradition computing batch systems as well as purpose-built data
transfer batch systems:
.TP
.B condor, stork
The Condor high throughput computing environment (required to use
stork data mover)
.TP
.B pbs, torque
The PBS family of batch systems (OpenPBS, PBS Pro, and TORQUE)
.TP
.B rft
Globus RFT (required to use rft data mover)
.PP
As described above, it is not necessary for
.B dmsub
to use the data mover associated with a given transfer description
format or vice versa.

.SH OPTIONS
.TP
.B -b rm, --batch=rm, --rm=rm
Use "rm" batch environment (default is torque)
.TP
.B -C cfgfile, --config=cfgfile
Read config file "cfgfile"
.TP
.B -c credfile, --credential=credfile
Use file "credfile" as GSI credential
.TP
.B -D jobid[:jobid], --dependency=jobid[:jobid]
Do not run data transfer job till after jobid completes
.TP
.B -d, --debug
Enable debugging output
.TP
.B -e errlog, --errlog=errlog
Write stderr from data transfer to "errlog"
.TP
.B -F fmt, --format=fmt
Use "fmt" as data transfer description format (default is urlpair)
.TP
.B -H, --hold
Submit job in held state if possible (default is False)
.TP
.B -h, --help
Print a help message
.TP
.B -j join, --joinlogs=join
Join stdout and stderr logs (default is None)
.TP
.B -l rsrc=limit[,rsrc=limit], --limit=rsrc=limit[,rsrc=limit]
Set batch resource limit (e.g. walltime)
.TP
.B -M mvr, --mover=mvr
Use "mvr" as the data movement mechanism (default is supermover)
.TP
.B -N jobname, --name=jobname
Use "jobnname" as name of data movement job
.TP
.B -n, --nosubmit
Do a dry run without submitting any jobs
.TP
.B -o log, --outlog=log
Write stdout from data transfer to "log"
.TP
.B -P pt, --port=pt
Connect to data transfer service on port "pt"
.TP
.B -q dest, --queue=dest
Submit data transfer job to batch queue "dest" (default is dmover)
.TP
.B -s n, --streams=n
Use up to "n" striped data streams whenever possible (default is 4)
.TP
.B -S svr, --server=svr
Connect to data transfer service on server "svr"

.SH CONFIG FILE

.B dmsub
uses a config file with a simple "keyword = value" syntax to set
system-wide defaults.  The following are valid keywords for it:
.TP
.B batch, rm
Default batch system, equivalent to --batch=
.TP
.B block_size
Default GridFTP block size
.TP
.B format
Default transfer description format, equivalent to --format=
.TP
.B mover
Default data mover, equivalent to --mover=
.TP
.B port
Default server port, equivalent to --port=
.TP
.B queue
Default queue, equivalent to --queue=
.TP
.B pbs_prologue
A set of commands to run at the beginning of every PBS/TORQUE job.
.TP
.B server
Default server, equivalent to --server=
.TP
.B streams
Default number of concurrent GridFTP data streams, equivalent to --streams=
.TP
.B stripe_size
Default GridFTP stripe size
.TP
.B walltime
Default walltime limit, equivalent to -l walltime=

.SH Config file example

.PP
# defaults
.fi
rm = torque
.fi
mover = supermover
.fi
queue = dmover
.fi
#format = stork
.fi
streams = 4
.fi
pbs_prologue = module load hsi\nmodule load globus
.fi
.PP

.SH AUTHOR
Troy Baer (tbaer (at) utk.edu)

.SH SEE ALSO
supermover(1)