.TH ja 1 "$Date$" "$Revision$" "PBS TOOLS"

.SH NAME
ja \- print job accounting information inside a PBS job

.SH SYNOPSIS
.B ja

.SH DESCRIPTION
Inside a PBS batch job, 
.B ja
queries the batch system for the current resources used.  This will
typically include CPU time (cput), real time (walltime), real memory
(mem), and virtual memory (vmem); other resources may also be reported
depending on the platform.

.SH EXAMPLES

In a batch job:
.PP
.B echo $PBS_JOBID
.nf
12345.pbs-server.company.com
.fi
.B ja
.nf
Job Id: 12345.pbs-server.company.com
    Job_Name = foo
    resources_used.cput = 00:00:00
    resources_used.mem = 4268kb
    resources_used.vmem = 4268kb
    resources_used.walltime = 00:03:22
.fi
.PP
Not in a batch job:
.PP
.B echo $PBS_JOBID
.nf
[none]
.fi
.B ja
.nf
ja: Not in a PBS job, exiting!
.fi


.SH AUTHOR
Troy Baer (tbaer (at) utk.edu)

.SH SEE ALSO
.BR qstat (1B)
